### ISSUE TITLE
Feature Request: rajzterületre ki-be-kapcsolható halvány rácsháló

### ISSUE THREAD

**Issue by tomzorz** [sedthh/schonherz-matrix#10]

**Comment by sedthh** [comment]
Valid, lesznek menthető beállítások, akkor hozzáadom settingsként. Layer invisibility és layer render ki- és bekapcsolást is akarok rakni, amíg arra nincs gomb, ez lett a fallback.

**Comment by sedthh** [comment]
Raktam be automatikusan megjelenő rácshálót, bizonyos szintű zoom után.
