### ISSUE TITLE
Feature Request: Rajzterület/felbontás skálázása SCH képarányra

### ISSUE THREAD

**Issue by tomzorz** [sedthh/schonherz-matrix#11]
Felbontást nézve a képarány kb 4:3, de a valóságban az épületen inkább olyan 3:5 arányban jelenik meg az animáció: jó lenne ha a rajzterület erre hasonlítana már szerkesztéskor. (most egy pixel 1:1 oldalarányú, ez így szerintem nem célszerű)

**Comment by sedthh** [comment]
Emiatt raktam mellé a jobb oldali preview ablakot, de valószínűleg igazad lesz és páran el fogják rontani a rajzaikat, hogy 1:1-ben rajzolják és rosszul jelenik majd meg életben, erre nem gondoltam.

Ha látványos lesz ez a hiba, akkor a Mátrix után csinálok ilyet.

**Comment by tomzorz** [comment]
Ez volt a fő bajom minden másik editorral amit láttam, hogy teljesen hiába van preview meg szép UI ha nem "wysiwyg" a dolog. 

Konkrétan csak emiatt akartam írni saját editort, hogy ez jó legyen :D Szerintem talán a legfontosabb dolog az alkalmazásban.

**Comment by sedthh** [comment]
Tudsz a preview ablakra is rajzolni. Azt is terveztem, hogy a LED falak hibáit is szimulálom kirajzoláskor, hogy még inkább wsyiwyg legyen a visszajátszás, csak túlságosan lelassítaná a Tkinter-t.

**Comment by sedthh** [comment]
0.1.5-től van ratio toggle (színpad nyújtása vagy 0 gomb)
