### ISSUE TITLE
Feature Request: Importálás videóból

### ISSUE THREAD

**Issue by tomzorz** [sedthh/schonherz-matrix#12]
ffmpeg barátunkkal viszonylag triviális feladat

**Comment by kiskoza** [comment]
importálás esetén rengeteg felkiáltójeles ablak szóljon előtte, hogy nem jó ötlet egy youtube videót beimportálni

**Comment by sedthh** [comment]
Kép importálás lesz benne, amiben be lehet majd állítani a konvertálási módokat és hogy figyelembe vegye-e például az ablakkereteket. Az a tapasztalatom, hogy videót csak snittenként lehet valamennyire beimportálni, mert minden scene külön trükközést igényel, hogy ne nézzen ki szarul. Van saját konvertálóm, ami konvolúciós filtereket is alkalmaz és azzal is nehezen látható a végeredmény, ha nem mozognak a filmben folyamatosan. 

Szóval kép importálás egyesével igen, videó importálás nem lesz benne, de workaroundként van qp4 LUA-ba konvertáló megoldás, akkor annak a végeredményét be lehet importálni az editorba.
