### ISSUE TITLE
Feature request: barátságosabb színválasztó

### ISSUE THREAD

**Issue by tomzorz** [sedthh/schonherz-matrix#13]
A mostani színválasztónál is lehet saját színeket elmenteni, de ezeket a beépített "add to custom colors" gombbal lehet a popup ablakban, ahol nem teljesen egyértelmű, hogy mit csinálunk és mit mire cserélünk le. 

Jobb lenne valami ilyesmi: 

[ AKTUÁLIS SZÍN ] - [ ALAP 1 ] ... [ ALAP n ] - [ SAJÁT 1 ] ... [ SAJÁT n ] [ új hozzáadása gomb ]

A sajátokra jobb kattintva context menüben: szerkesztés, eltávolítás

**Comment by sedthh** [comment]
Jobb clickre színkeverést hozzáadtam, a hozzáadás/eltávolítást azért nem támogatom, mert: 
1) lesz aki kiesbb ablakban nyitja majd meg és nem fogja észrevenni a további felvett színeket
2) direkt limitálni akartam a palettát, hogy jobb pixel artokat csináljanak a limitációkhoz alkalmazkodva
3) a kijelző ha jól tudom továbbra is 4096 színű, ezért akármilyen színt (főleg szürkeárnyalatokat) amúgy sem tudnának megjeleníteni, hiába keverik ki pluszban

**Comment by tomzorz** [comment]
A 3. jó pont, de ennek megfelelően én pl. nem a windowsos color pickert használnám. Én sem emlékeztem már, hogy hány szín van és mit nem tudunk megjeleníteni -> ha már alapból az alkalmazás nem kínálja fel a  nem megjeleníthető színeket az UX+++

**Comment by sedthh** [comment]
Így is volt tervben, hogy alapból csak a megjeleníthető színeket ajánlja fel, de akkor saját color pickert is írnom kellett volna még, amire nem volt időm. Ha van ilyened vagy color wheeled, akkor nyugodtan tedd hozzá.

**Comment by tomzorz** [comment]
Pythonhoz minimálisan értek, a használt frameworkről meg nem is hallottam - sajnos nem én leszek aki neked ebben segít :D
