### ISSUE TITLE
Teljes képkocka kitöltése (háttér változtatás)

### ISSUE THREAD

**Issue by kiskoza** [sedthh/schonherz-matrix#15]
Verzió: 0.1.1 Alpha

Egy teljesen üres képkockán nem működik a "festékes vödör".

Lépések:
1) Szerkesztőt megnyitod
2) Fehér színre váltasz (az alapértelmezett képkocka fekete)
3) Festékes vödörrel kitöltöd az egészet
4) (Hiba) Fekete maradt a képkocka

Kapcsolódó hiba: alakzaton kívüli részek kitöltése
1) Rajzolj egy zárt alakzatot
2) Próbáld meg kitölteni az alakzaton kívüli részt

**Comment by sedthh** [comment]
Ez direkt van így, mert nem fekete színt látsz, hanem üres pixeleket minden irányba. Alakzaton belüli ürességet ki lehet tölteni.

**Comment by kiskoza** [comment]
Szerintem ez egy reális use-case, ilyenkor a látható terület köré nem lehet egy keretet virtuálisan odatenni és azon belül kiszínezni? Vagy egy üzenettel jelezni, hogy "Csak zárt alakzatok kitöltése engedélyezett".

**Comment by sedthh** [comment]
Látható területnek csak a preview ablakban van értelme. Rectangle tool-lal lehet rakni beszínezett négyszöget.

**Comment by tomzorz** [comment]
@sedthh akkor viszont ez egy UX issue, mert a user nem tudja megkülönböztetni a feketét az ürestől. Esetleg lehetne a pixelekbe egy halvány áthúzást rakni ilyenkor átlósan.

**Comment by sedthh** [comment]
Egyetértek, de nem volt jobb ötletem, hogy milyen legyen a háttérszín, mert ha magenta/világoszöld akkor meg azok vesznek el/máshogy néz ki olyan háttérrel amit rajzolsz, mint a végeredmény.

Átlátszóságot jelző patternen gondolkodtam még, csak azt renderelni megint plusz erőforrás.

**Comment by tomzorz** [comment]
@sedthh crysis-t renderelni erőforrásigényes, azért egy pixelartot bírjon már el bármi még egy áthúzott vonallal is :)

**Comment by sedthh** [comment]
szkript nyelvből hákolt API-val aktuális oprendszer valahol karbantartott ablakkezelőjének a canvas rajzolójába objektumokat felvinni szoftveresen pixelek helyett, az is erőforrásigényes

**Comment by tomzorz** [comment]
@sedthh akkor rosszul választottál UI frameworköt ;)

**Comment by sedthh** [comment]
ez a legjobb UI framework Pythonra
