### ISSUE TITLE
Feature request: több, mint egy hang file hozzáadása

### ISSUE THREAD

**Issue by actualbleach11** [sedthh/schonherz-matrix#17]
Tök menő lenne, hogyha lenne hangsáv is, ahol a hangot hozzá lehet igazítani a videóhoz, és akár többet is egymás után rakni.

**Comment by sedthh** [comment]
Szia, ti csináltátok a zenés klippet, amiben énekeltek, hogy diplomázz le? Ha igen, akkor megírnád, hogy még mit változtatnál az editoron, mi volt az, ami nem igazán állt kézre?

**Comment by actualbleach11** [comment]
Szia! Azt sajnos nem mi csináltuk. 
De az volt a helyzet, hogy több különálló hangfileunk volt, amit egymás után akartunk lejátszani, és először össze kellett mergelni, hogy a szerkesztőbe bele tudjuk tenni az egészet. 
Amikor ezt írtam, akkor valami olyasmire gondoltam, mint amilyen régen a Windows Movie Maker szerkesztőben volt, hogy a képsáv mellett volt egy hangsáv is, ahol a legalapabb hangvágásokat meg lehetett csinálni. (pl egymás után rakni, elejét/végét levágni, videóhoz igazítani)

**Comment by sedthh** [comment]
Értem, köszi. A waveform kirajzolására én is gondoltam, az összevágásra nem, de gondolkodni fogok rajt. Egyéb tapasztalat?

**Comment by sedthh** [comment]
> Amikor ezt írtam, akkor valami olyasmire gondoltam, mint amilyen régen a Windows Movie Maker szerkesztőben volt, hogy a képsáv mellett volt egy hangsáv is, ahol a legalapabb hangvágásokat meg lehetett csinálni. (pl egymás után rakni, elejét/végét levágni, videóhoz igazítani)

Hangsáv waveformja most már látszik a szerkesztőben, a több hang összevágását meg lehetne oldani, [de sokkal jobb ingyenes szoftverek vannak erre](https://www.audacityteam.org/), ezért fölösleges lenne külön írni egyet.
