### ISSUE TITLE
Az egérgörgő mozgatása a rajztéren belül színt vált

### ISSUE THREAD

**Issue by tomzorz** [sedthh/schonherz-matrix#5]
Jó lenne ha ezt ki lehetne kapcsolni.

**Comment by tomzorz** [comment]
Vagy legalább a lenti listán egy kis keretet mozgatni, hogy lássam most merre váltok éppen.

**Comment by sedthh** [comment]
A kiválasztott szín körül most piros keret jelenik meg, hogy jobban látszódjon 👌
