### ISSUE TITLE
Teljes képernyős módból a címsort megfogva és lehúzva nem lehet elmozgatni/kimozdítani az alkalmazást Windows alatt

### ISSUE THREAD

**Issue by tomzorz** [sedthh/schonherz-matrix#8]

**Comment by sedthh** [comment]
Ezt nem értem, bővebben pls

**Comment by tomzorz** [comment]
Csináltam videót (kattints nagy felbontásért): https://gfycat.com/CarelessArcticEel

[![issue](https://thumbs.gfycat.com/CarelessArcticEel-size_restricted.gif)](https://gfycat.com/CarelessArcticEel)

**Comment by sedthh** [comment]
Wow tényleg aprólékosan átnézted amit lehetett 👌

Ez a Tkinter-nek lehet a hiányossága, ami az ablakot generálja, de lehet, hogy workaround-dal bele lehet rakni, hogy manuálisan lekezeljem ezt.

**Comment by tomzorz** [comment]
Az aprólékos túlzás, inkább gyakran használom ezeket a snap mozdulatokat monitorok között :)
