### ISSUE TITLE
Ékezetes betűk hiányoznak a választott fontból Windows alatt

### ISSUE THREAD

**Issue by tomzorz** [sedthh/schonherz-matrix#9]
![image](https://user-images.githubusercontent.com/6363312/45592572-d7eee200-b971-11e8-9aaa-8f7396cedc01.png)

**Comment by sedthh** [comment]
Hol?

**Comment by tomzorz** [comment]
Hiányzik = a rendszer másikra cserélte. 

A screenshoton látod, bár igazából ha jobban megnézed minden ékezetes font máshonnan jön. (ezt már reggel 6kor félálomban nem vettem észre...)

**Comment by sedthh** [comment]
Most látom, hogy tényleg azok más betűtípusból vannak, még jó, hogy "system" a font neve. Javítom majd.

**Comment by tomzorz** [comment]
@sedthh mert Win 3.1 alatt volt használva https://en.wikipedia.org/wiki/System_(typeface)

Windows Vista óta a Segoe UI a standard, azt javasolnám mindenhová.

**Comment by sedthh** [comment]
de az ugyanúgy nincs Ubuntun és MacOS X-en, azért ezt az alapot használtam, hogy kb ugyanúgy nézzen legalább ki mindenhol

**Comment by sedthh** [comment]
Kicseréltem Helvetica betűtípusra.

**Comment by tomzorz** [comment]
@sedthh olyan nincs Windows alatt csak Mac alatt. Verdana-t vagy Tahoma-t javasolnám ha mindenáron ugyanazt akarod, azok voltak a régebbi UI fontok.

**Comment by sedthh** [comment]
Elvileg fallbackel Arial-ra Windows alatt, ha nincs.

**Comment by tomzorz** [comment]
Sounds good, majd este ránézek otthon ha eszemben lesz.
